import type { SliceBurstEvent } from "../events/SliceBurstAggregator";

export interface SliceAudioSink {
  playSfx(
    name: "slice" | "bomb",
    options?: { volume?: number; playbackRate?: number; maxVoices?: number }
  ): void;
  getActiveVoiceCount?(name: "slice" | "bomb"): number;
}

export interface SliceAudioTuningConfig {
  baseVolume: number;
  basePitch: number;
  baseMaxVoices: number;

  combo2Pitch: number;
  combo2Volume: number;

  combo3Pitch: number;
  combo3Volume: number;

  combo4Pitch: number;
  combo4Volume: number;

  bombVolume: number;
  bombPitch: number;
  bombMaxVoices: number;
}

/**
 * Initial tuning hypotheses — named constants, not dogmatic standards.
 */
export const DEFAULT_SLICE_AUDIO_CONFIG: SliceAudioTuningConfig = {
  baseVolume: 0.75,
  basePitch: 1.0,
  baseMaxVoices: 4,

  combo2Pitch: 1.05,
  combo2Volume: 0.80,

  combo3Pitch: 1.10,
  combo3Volume: 0.85,

  combo4Pitch: 1.16,
  combo4Volume: 0.90,

  bombVolume: 0.85,
  bombPitch: 1.0,
  bombMaxVoices: 2,
};

export class SliceAudioPolicy {
  constructor(
    private sink: SliceAudioSink,
    private config: SliceAudioTuningConfig = DEFAULT_SLICE_AUDIO_CONFIG,
    private debug = false
  ) {}

  handleEvents(events: SliceBurstEvent[]): void {
    if (!events || events.length === 0) return;

    // Batch-level priority:
    // If a BOMB_HIT occurs anywhere in this event batch, suppress all slice/combo audio
    // generated by this same batch and trigger bomb SFX exactly once.
    const hasBomb = events.some((event) => event.type === "BOMB_HIT");
    if (hasBomb) {
      this.sink.playSfx("bomb", {
        volume: this.config.bombVolume,
        playbackRate: this.config.bombPitch,
        maxVoices: this.config.bombMaxVoices,
      });
      this.logDebug("BOMB_HIT (batch-priority)", "bomb", this.config.bombPitch);
      return;
    }

    for (const event of events) {
      this.handleEvent(event);
    }
  }

  handleEvent(event: SliceBurstEvent): void {
    switch (event.type) {
      case "BURST_STARTED": {
        // Immediate first-hit feedback
        const { pitch, volume } = this.getPitchAndVolumeForCount(event.count);
        this.sink.playSfx("slice", {
          volume,
          playbackRate: pitch,
          maxVoices: this.config.baseMaxVoices,
        });
        this.logDebug("BURST_STARTED", "slice", pitch);
        break;
      }

      case "BURST_EXTENDED": {
        // Combo / accent behavior on subsequent hits within the same perceived slash
        const { pitch, volume } = this.getPitchAndVolumeForCount(event.count);
        this.sink.playSfx("slice", {
          volume,
          playbackRate: pitch,
          maxVoices: this.config.baseMaxVoices,
        });
        this.logDebug("BURST_EXTENDED", "slice", pitch);
        break;
      }

      case "BOMB_HIT": {
        // Bomb takes highest priority.
        // Audible rationale: The slice SFX is naturally short (~200ms) with decay.
        // Forcibly calling stop() on all voices can introduce digital clicks/pops without gain ramps.
        // Playing bomb with max volume (0.96) psychoacoustically masks the decaying slice sound,
        // and burst cancellation prevents any future slice sounds in this stroke.
        this.sink.playSfx("bomb", {
          volume: this.config.bombVolume,
          playbackRate: this.config.bombPitch,
          maxVoices: this.config.bombMaxVoices,
        });
        this.logDebug("BOMB_HIT", "bomb", this.config.bombPitch);
        break;
      }

      case "BURST_ENDED": {
        // Semantic summary event only; no extra sound needed on burst close
        break;
      }
    }
  }

  private getPitchAndVolumeForCount(count: number): { pitch: number; volume: number } {
    if (count >= 4) {
      return { pitch: this.config.combo4Pitch, volume: this.config.combo4Volume };
    }
    if (count === 3) {
      return { pitch: this.config.combo3Pitch, volume: this.config.combo3Volume };
    }
    if (count === 2) {
      return { pitch: this.config.combo2Pitch, volume: this.config.combo2Volume };
    }
    return { pitch: this.config.basePitch, volume: this.config.baseVolume };
  }

  private logDebug(event: string, sound: string, pitch: number): void {
    if (!this.debug) return;
    if (typeof process !== "undefined" && process.env?.NODE_ENV === "production") return;
    const activeVoices = this.sink.getActiveVoiceCount ? this.sink.getActiveVoiceCount(sound as any) : "N/A";
    console.debug(`[SliceAudio] event=${event} sound=${sound} pitch=${pitch.toFixed(2)} activeVoices=${activeVoices}`);
  }
}
